# Generated by Django 5.1.2 on 2024-11-04 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependents',
            fields=[
                ('iddependents', models.AutoField(db_column='idDependents', primary_key=True, serialize=False)),
                ('card_number', models.IntegerField(db_column='Card_Number')),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('surname', models.CharField(db_column='Surname', max_length=100)),
            ],
            options={
                'db_table': 'Dependents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainMembers',
            fields=[
                ('card_number', models.IntegerField(db_column='Card_Number', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('surname', models.CharField(db_column='Surname', max_length=100)),
                ('address', models.CharField(db_column='Address', max_length=100)),
                ('phone_number', models.CharField(blank=True, db_column='Phone_Number', max_length=45, null=True)),
                ('branch', models.CharField(db_column='Branch', max_length=100)),
                ('gender', models.CharField(db_column='Gender', max_length=45)),
                ('registration_year', models.IntegerField(blank=True, db_column='Registration_Year', null=True)),
                ('number_of_dependants', models.IntegerField(db_column='Number_Of_Dependants')),
                ('branch_member_number', models.CharField(blank=True, db_column='Branch_Member_Number', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Main_Members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Treasury',
            fields=[
                ('idtreasury', models.AutoField(db_column='idTreasury', primary_key=True, serialize=False)),
                ('idmain_member', models.IntegerField(db_column='idMain_Member')),
                ('fund', models.CharField(db_column='Fund', max_length=45)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('fund_date_year', models.IntegerField(db_column='Fund_Date_Year')),
                ('fund_date_month', models.CharField(db_column='Fund_Date_Month', max_length=50)),
                ('receipt_number', models.IntegerField(db_column='Receipt_Number')),
                ('payment_date', models.DateField(db_column='Payment_Date')),
            ],
            options={
                'db_table': 'Treasury',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TreasuryDep',
            fields=[
                ('idtreasury_dep', models.AutoField(db_column='idTreasury_Dep', primary_key=True, serialize=False)),
                ('card_number', models.IntegerField(db_column='Card_Number')),
                ('dependent_id', models.IntegerField(db_column='Dependent_ID')),
                ('fund', models.CharField(db_column='Fund', max_length=50)),
                ('amount', models.IntegerField(db_column='Amount')),
                ('fund_date_year', models.IntegerField(db_column='Fund_Date_Year')),
                ('fund_date_month', models.IntegerField(db_column='Fund_Date_Month')),
                ('reciept_number', models.IntegerField(db_column='Reciept_Number')),
                ('payment_date', models.DateField(db_column='Payment_Date')),
            ],
            options={
                'db_table': 'Treasury_Dep',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Logged In'), ('PAYMENT', 'Payment Made')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
