# Generated by Django 5.1.2 on 2024-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPictures',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture_data', models.BinaryField(null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Member_Pictures',
                'managed': False,
            },
        ),
    ]
